// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojxspevfoclwdxuhjfes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeHNwZXZmb2Nsd2R4dWhqZmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjgxNjUsImV4cCI6MjA2ODMwNDE2NX0.NFtz9M-v5VUuJaDS4KlIUHIVZ_wqG7DYaT5AgV27rUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});